### ISSUE TITLE
[String] Allow concatenating strings in one way or the other

### ISSUE THREAD

**Issue by ldionne** [boostorg/hana#117]
It could be via `Monoid` or via `MonadPlus`. I don't like concatenating `String`s with `plus`, but at the same time it is perfectly sound mathematically speaking. If we're able to make it a `MonadPlus` and use `concat`, that would be better (but it has to satisfy the laws).

**Comment by ricejasonf** [comment]
We could make a new concept `IntegralSequence<T>`, add impls for all functions for concepts that `Sequence` refines and add it in the concept checks for each of those functions. (a `TypeSequence` would be cool too)
