### ISSUE TITLE
[Associative Sequence] Consider using hash-based structures

### ISSUE THREAD

**Issue by ldionne** [boostorg/hana#118]
See [this](http://article.gmane.org/gmane.comp.lib.boost.devel/261170) post on the mailing list.

**Comment by ldionne** [comment]
Also have a look at [this](https://github.com/ldionne/hana/blob/2c1bb3a607dc03489d5f68df65f36cd65510d8dc/include/boost/hana/detail/sandbox/map.hpp) old implementation of a hash-based Map in the sandbox.

**Comment by ricejasonf** [comment]
I was thinking that the point of **normalizing** the integral_constants was to make `m[size_c<5>] == m[int_c<5>]'. If the buckets contain a list of elements that are linearly searched using `Comparable` then it seems pointless to `int_c<5>` and `size_c<5>` in the same bucket. Is there ever a case where two `IntegralConstants` will be equal but have different types?

**Comment by ricejasonf** [comment]
I would like to add some tests for the above when you get back to me on the desired behaviour. I would also add tests the check that `map` ultimately uses `Comparable`, but I argue that there is no realistic use case for that.

**Comment by ldionne** [comment]
I will close this, as this is currently being considered in #242.
