### ISSUE TITLE
Provide examples of migrations to Hana

### ISSUE THREAD

**Issue by ldionne** [boostorg/hana#142]
It would be nice if the tutorial could provide examples of migrations to Hana from hand-written code and from Fusion/MPL code too.

**Comment by ricejasonf** [comment]
I have a bunch of hand written junk. :P 

https://gist.github.com/ricejasonf/3572a9ded591e8767f3a

**Comment by ldionne** [comment]
I won't add examples of transitions, since in most cases it's easier to rewrite using a different paradigm. However, I'll add links to existing projects using Hana.
