### ISSUE TITLE
[Tutorial] Document how hana::when can be used to spice up tag-dispatched methods

### ISSUE THREAD

**Issue by ldionne** [boostorg/hana#173]

**Comment by FrankHB** [comment]
Is it true that `void_t` + `enable_if_t` is not enough here?

**Comment by ldionne** [comment]
You're wondering whether `when<>` is equivalent to `void_t` + `enable_if`? They are not, because using `when<>` allows us to add an extra level of priority for partial specializations. Specifically, here's how we do it:

```c++
template <typename T, typename = void>
struct Foo;

template <typename T>
struct Foo<T> : Foo<T, when<true>> { };
```

Then, when partially specializing `Foo`, you have three choices. The first one is explicit specialization:

```c++
template <>
struct Foo<hana::tuple<int>> { };
```

This has the highest priority, in the sense that `Foo<hana::tuple<int>>` will now refer to that specialization. The second level is a normal partial specialization:

```c++
template <typename ...T>
struct Foo<hana::tuple<T...>> { };
```

Now, `Foo<hana::tuple<int>>` would still refer to the first one, but `Foo<hana::tuple<float>>` would refer to the second one. This third one is `when`-based specialization:

```c++
template <typename Ts>
struct Foo<Ts, hana::when<hana::Sequence<Ts>::value>> { };
```

Now, `Foo` will work with anything that is a `Sequence`. When it is used with a `hana::tuple`, however, the second one will be preferred. However, if we used 

```c++
template <typename Ts>
struct Foo<Ts, std::void_t<std::enable_if_t<hana::Sequence<Ts>::value>>> { };
```

then using `Foo` with a `hana::tuple` would be ambiguous, because both this specialization and the one for `tuple<T...>` would match.

**Comment by FrankHB** [comment]
Got it. Thanks.
