### ISSUE TITLE
Consider renaming `if_` and `while_` to `static_if` and `static_while`

### ISSUE THREAD

**Issue by ldionne** [boostorg/hana#185]

**Comment by vendethiel** [comment]
Why? Could they be dynamic (and still be in hana)?

**Comment by ahundt** [comment]
for statements that would be used frequently like those I would lean towards the current names

**Comment by ldionne** [comment]
> Why? Could they be dynamic (and still be in hana)?

Currently, `if_` and `while_` can be used with runtime boolean conditions too, so indeed `static_xxx` would be a bad name. However, I'm looking at the possibility of only supporting `integral_constant`-like conditions for a first release, because that would allow simplifying the `Logical` concept, which I don't like all that much.

> for statements that would be used frequently like those I would lean towards the current names

From my experience, those statements are not used all that frequently. `while_` definitely isn't, and `if_` is slightly more common but not that bad. If using `static_if` can add clarity, that should be the main goal. Note that this is motivated by a comment by someone during my CppCon talk; I was explaining code with an `if_` in it, and when a person asked me whether that was _basically a static if_, it made everything much simpler I think.

**Comment by ldionne** [comment]
Screw this for now; let's not lose generality by implying that they can only be used with `IntegralConstant`s. There does not seem to be a sufficiently compelling reason to rename them.
