### ISSUE TITLE
hana on homebrew

### ISSUE THREAD

**Issue by autosquid** [boostorg/hana#195]
could you please make hana an installable package so we can easily install from homebrew before it appears in boost?

**Comment by ldionne** [comment]
I actually did not mean to close this yet. I'll close it when/if the formula is added to Homebrew.

**Comment by autosquid** [comment]
oh, I did not expect it to be that simple to be honest.  The boost and compiler setting creeps me out..

**Comment by ldionne** [comment]
Hana has no dependencies on other libraries, so I don't have to build anything else. And since it's header only, installing is just a matter of copying a couple of files around.

**Comment by cbeck88** [comment]
:+1: thanks for this!
