### ISSUE TITLE
[license] [doc] [doxygen] Unlicensed source code files in hana/doc

### ISSUE THREAD

**Issue by badair** [boostorg/hana#228]
I noticed the following source code files do not include a license statement:

hana/doc/Doxyfile.in
hana/doc/footer.html
hana/doc/header.html
hana/doc/layout.xml
hana/doc/mathjax-config.js
hana/doc/tutorial.hpp

Is this an intentional omission? I would like to use them as a launchpad for documentation for my toy project, but I assume that I can't legally copy them in their current state. 

If you intend to open source them, I can submit a Hana PR adding 'Copyright Louis DIonne 2015' lines and Boost license statements to the tops of these files.

**Comment by ldionne** [comment]
Thanks!

**Comment by badair** [comment]
Awesome, thank you!
