### ISSUE TITLE
question about group, monoid, ring etc

### ISSUE THREAD

**Issue by robertramey** [boostorg/hana#243]
Looking through the documentation carefully for the first time it's starting to make some sense for me.

In the reference - Concepts - I find group, mooned, ring etc.  But searching through the documentation I don't find anywhere where these concepts are actually used.  It's quite possible that they are used somewhere but I haven't found them - if so , how about a pointer.  On the other hand, if they are not actually used - what is the purpose of having them here?

Robert Ramey

**Comment by ricejasonf** [comment]
Under `Reference documentation -> Data Types`, each data type has a section called "Modeled Concepts".

**Comment by ldionne** [comment]
^ What he said. You'll find for example `hana::integral_constant`, which models everything from `Monoid` to `EuclideanRing`.
