### ISSUE TITLE
Can I break the hana:for_each?

### ISSUE THREAD

**Issue by harrywong** [boostorg/hana#245]
Hi, can I find any way to break out of hana:for_each? I tried goto but it's not valid, I think it's the lambda-things.
Thanks!

**Comment by ldionne** [comment]
No, you can't break out of a `hana::for_each`, just like you can't break out of `std::for_each`. Both are higher order functions accepting the body of the loop, and there is no way I know of to break from that in C++.

**Comment by pfultz2** [comment]
Well, the lambda could return a value to signify whether it should continue or stop:

```cpp
for_each(seq, [](auto x)
{
    if(x)
    {
        run(x);
        return continue_;
    }
    else return break_;
};
```

But it might be better to use `take_while` then `for_each`.

**Comment by ldionne** [comment]
The problem with this is that it would make the algorithm much less compile-time efficient. I think the only way to implement it while allowing one to break is to use a recursive function, and that's a no-no.

I think the proper way to go would be to use `take_while` and then `for_each`, as you suggest. However, `take_while` is going to make a copy of the sequence. If we had a `take_while` sort of view, we could create a `take_while` view and then use `for_each` on it without additional runtime overhead.

**Comment by ldionne** [comment]
@pfultz2 Do you know of any way to implement your suggestion while still retaining the near optimal compile-times of a simple `for_each`?

**Comment by vendethiel** [comment]
```c++
bool continue = true;
for_each(seq, [](auto x)
{
  if (!continue) return;
  if (run(x)) continue = false;
};
```

:P

**Comment by pfultz2** [comment]
> Do you know of any way to implement your suggestion while still retaining the near optimal compile-times of a simple for_each?

I don't, which is why I suggested `take_while` as a more efficient route.
