### ISSUE TITLE
Some std::make_index_sequence implementations are O(N)

### ISSUE THREAD

**Issue by hpesoj** [boostorg/hana#257]
I am currently using Boost.Hana with Clang 3.7.1 and the GCC standard library. The length of `hana::tuple` is currently limited because `std::make_index_sequence` has O(N) recursion complexity. I have no idea if libc++ has a better implementation, but you could support larger containers with a wider range of standard library implementations if you implemented your own `make_index_sequence` with O(log N) complexity, like this for example:

    #include <utility>

    template<typename S1, typename S2>
    struct build_index_sequence;

    template<typename S1, typename S2>
    using build_index_sequence_t = typename build_index_sequence<S1, S2>::type;

    template<
        std::size_t... Cs1,
        std::size_t... Cs2
    >
    struct build_index_sequence<
        std::index_sequence<Cs1...>,
        std::index_sequence<Cs2...>
    >
    {
        using type = std::index_sequence<Cs1..., sizeof...(Cs1) + Cs2...>;
    };

    template<std::size_t N>
    struct make_index_sequence;

    template<std::size_t N>
    using make_index_sequence_t =
        typename make_index_sequence<N>::type;

    template<std::size_t N>
    struct make_index_sequence
    {
        using type = build_index_sequence_t<
            make_index_sequence_t<N / 2>,
            make_index_sequence_t<N - N / 2>
        >;
    };

    template<>
    struct make_index_sequence<1>
    {
        using type = std::index_sequence<0>;
    };

    template<>
    struct make_index_sequence<0>
    {
        using type = std::index_sequence<>;
    };

**Comment by ricejasonf** [comment]
For me `std::make_index_sequence` on libstdc++ explodes at around 250 elements, but with libc++ it works fine until well into the hundred thousands. (which is more a limit on variadic templates)

Coincidentally, we were just playing around with this in the chat yesterday.

**Comment by ricejasonf** [comment]
I tried the above implementation on that same test. It still explodes on libstc++ and it doesn't scale as well as the libc++ version.

**Comment by hpesoj** [comment]
Sorry, I did mean libc++, not libstdc++.

`std::make_index_sequence` also explodes at around 250 elements for me. The implementation I provided, however, crashes the compiler before it hits any recursion limit. Are you sure you tested it correctly?

As for whether it scales as well as the libc++ version, I wouldn't be surprised if they have a better implementation. I just know that libstdc++ doesn't scale well.

**Comment by ricejasonf** [comment]
Yeah sorry, the above implementation doesn't explode until between 500-600.

**Comment by hpesoj** [comment]
Strange. This compiles fine for me:

    using t = make_index_sequence_t<1000000>;

**Comment by ricejasonf** [comment]
Okay.. I fixed my test. I was calling `std::make_index_sequence` inside my `filter` function. It is actually pretty close on libc++ and works just fine on libstdc++ (actually faster but it is a different box)

Sorry about that :sweat_smile:

**Comment by hpesoj** [comment]
No problem!

I don't know what the performance difference is compared to libc++, but this implementation seems to run a bit faster for high element counts:

```
#include <utility>

template<typename S1, typename S2>
struct build_index_sequence;

template<typename S1, typename S2>
using build_index_sequence_t = typename build_index_sequence<S1, S2>::type;

template<std::size_t... Cs1, std::size_t... Cs2>
struct build_index_sequence<
    std::index_sequence<Cs1...>,
    std::index_sequence<Cs2...>
>
{
    using type = std::index_sequence<
        Cs1...,
        sizeof...(Cs1) + Cs1...,
        2 * sizeof...(Cs1) + Cs2...
    >;
};

template<std::size_t N>
struct make_index_sequence;

template<std::size_t N>
using make_index_sequence_t = typename make_index_sequence<N>::type;

template<std::size_t N>
struct make_index_sequence
{
    using type = build_index_sequence_t<
        make_index_sequence_t<N / 2>,
        make_index_sequence_t<N % 2>
    >;
};

template<>
struct make_index_sequence<1>
{
    using type = std::index_sequence<0>;
};

template<>
struct make_index_sequence<0>
{
    using type = std::index_sequence<>;
};
```

**Comment by ldionne** [comment]
Wouldn't it be better to submit a bug report to GCC so they improve their implementation? That would fix the problem for Hana and all other libraries using `std::make_index_sequence`, and wouldn't require us to reinvent the wheel. Note that Hana actually used to implement its own `std::make_index_sequence` (and also all of `<type_traits>`). It was decided that it was better to use the standard library, and rely on the fact that standard libraries have quality implementations.

I'd suggest you open a bug report against libstdc++ and link to this issue. If they don't want to move (which won't happen), then we'll see if it's worth adding a workaround in Hana.

**Comment by hpesoj** [comment]
I agree. I will file a bug with GCC.

**Comment by krzysztof-jusiak** [comment]
The newest libstdc++ has it fixed -> https://gcc.gnu.org/ml/libstdc++/2015-11/msg00129.html
However, it still will be much slower than the newest clang builtin `__make_integer_seq`, but, at least, it's not O(N) anymore

**Comment by ldionne** [comment]
@krzysztof-jusiak Thanks for the info. I'll close this then.
