### ISSUE TITLE
Concepts should inherit from `hana::integral_constant`

### ISSUE THREAD

**Issue by ldionne** [boostorg/hana#269]
Right now, concepts only provide a nested `::value` static member, which is not idiomatic. Instead, they should inherit from `hana::integral_constant`, but that might raise some circular dependencies issues.

Another take on this is that on the contrary, we don't want the concepts to inherit from an integral constant class, since we'll eventually move to C++17 concepts, and the migration will be easier if we only provide a `::value` member.

**Comment by ricejasonf** [comment]
I recently did something like `using type = hana::bool_c<value>;` in a concept so I could use it in `hana::trait<Concept>`.

**Comment by ldionne** [comment]
Ok, I'll implement this. But not in 1.0, because I'm freezing master until Boost 1.61 is out.

**Comment by ldionne** [comment]
I really want to avoid doing something stupid that I can't undo easily for that version.

**Comment by pfultz2** [comment]
Having the concepts be integral constants would help them play nicer with the rest of hana, if the user would want to, say for example, use them in a predicate to filter.
