### ISSUE TITLE
basic_type or type?

### ISSUE THREAD

**Issue by viboes** [boostorg/hana#274]
http://boostorg.github.io/hana/structboost_1_1hana_1_1type.html defines the class template `type` while I believe that it should be `basic_type`.

Should the data types index `type`or `basic_type`?

**Comment by ricejasonf** [comment]
`hana::type` is just a type alias template of a struct that is derived from `hana::basic_type`.

Consider the following snippet:
```
    template <typename T>
    struct type_impl {
        struct _ : basic_type<T> { };
    };

    template <typename T>
    using type = typename type_impl<T>::_;
```

The reason for this is that it's representation is meant to be implementation defined.

**Comment by viboes** [comment]
OK. 

Wondering if  `basic_type` merits an entry on the index of Data Types.

**Comment by ricejasonf** [comment]
Oh I see. I'm not sure. As far as I can tell the separation of `type` and `basic_type` is a hack for "subtle reasons having to do with the ADL", and `basic_type` is not to be used on its own. I could be very wrong though.

**Comment by viboes** [comment]
The documentation says that the functions taking a type must use `basic_type<T>`, so it merits to be in the index IMHO.

**Comment by ldionne** [comment]
As Jason suggested, `basic_type` should only be used for pattern matching on `hana::type`s. I feel like giving it its own Index entry would give it too much importance.

If I had to re-do this part of Hana, I think I would make `hana::type` equivalent to the current `hana::basic_type`, and would provide a `hana::protect` alias equivalent to the current `hana::type` to handle the subtle ADL cases.

**Comment by pfultz2** [comment]
> If I had to re-do this part of Hana, I think I would make hana::type equivalent to the current hana::basic_type, and would provide a hana::protect alias equivalent to the current hana::type to handle the subtle ADL cases.

I like this, perhaps for Hana 2.0.
