### ISSUE TITLE
Why type_c and not just type

### ISSUE THREAD

**Issue by viboes** [boostorg/hana#275]
What was the rationale to name the type wrapper function `type_c` and not just `type`?

**Comment by ricejasonf** [comment]
`hana::type_c` is a constexpr variable template. I believe the suffix '_c' is used to denote a constexpr value as you will see with others like `hana::int_c`, `hana::bool_c`, and even the user defined literals like '5_c'.

**Comment by viboes** [comment]
Thanks for the explanation.
