### ISSUE TITLE
Is there something like std::is_callable in Hana?

### ISSUE THREAD

**Issue by viboes** [boostorg/hana#277]

**Comment by ricejasonf** [comment]
I don't think so. There is a collection of hana wrapped traits in traits.hpp, but `std::is_callable` is not in there. Wrapping it in `hana::trait` is pretty simple though. The function will return an `IntegralConstant`.
```
constexpr auto is_callable = hana::trait<std::is_callable>{};

BOOST_HANA_CONSTANT_CHECK(is_callable(hana::type_c<blah>));
```

**Comment by ricejasonf** [comment]
There is also this, but I have not had a chance to use it much.

https://github.com/badair/callable_traits

**Comment by pfultz2** [comment]
The Fit library does provide [`is_callable`](http://fit.readthedocs.io/en/latest/is_callable/index.html), and it works for any [`Callable`](http://fit.readthedocs.io/en/latest/concepts/index.html#callable).

**Comment by viboes** [comment]
@ricejasonf Yes, but `std::is_callable` is C++1z ;-)
@ricejasonf The `is_callable` in CallableTraits doesn't use `std::invoke`/`INVOKE`
@pfultz2 What about adapting it to the C++1z style?
@pfultz2 We need `std::invoke` in Boost :)

**Comment by pfultz2** [comment]
> @pfultz2 What about adapting it to the C++1z style?

What is C++1z style?

> @pfultz2 We need std::invoke in Boost :)

There is [`boost::hana::apply`](http://boostorg.github.io/hana/group__group-functional.html#ga30027c383676084be151ef3c6cf2829f).

**Comment by badair** [comment]
@viboes The `is_callable` in CallableTraits was a misnomer, and has been removed entirely on the develop branch. The `is_invokable` function on the develop branch is logically equivalent to `std::is_callable`, and it is defined in terms of `std::invoke`. It works for many compilers. It probably needs to be renamed to `is_callable`, or (more likely) removed entirely (since apparently Fit has this covered already). I'm in the process of removing pieces of the library and dumping them into standalone headers, and I'll likely do the same with this.

**Comment by pfultz2** [comment]
> @pfultz2 What is the compiler support for Fit's is_callable? If you want, I could see about merging our implementations to include support for Visual Studio (if it isn't already supported).

Its supported on MSVC 2015. The Fit library doesn't support an earlier version of MSVC, so I've never tested it.

**Comment by viboes** [comment]
@pfultz2 http://en.cppreference.com/w/cpp/types/is_callable

boost::hana::apply. don't takes invoke in account :(

**Comment by pfultz2** [comment]
> @pfultz2 http://en.cppreference.com/w/cpp/types/is_callable

I see, well the `is_callable<F(Ts...)>` style will never happen. It is problematic and should never be used.

> boost::hana::apply. don't takes invoke in account :(

What do you mean? The docs say it is equivalent.

**Comment by viboes** [comment]
@pfultz2 Right. I was confused by

```
= [](auto&& f, auto&& ...x) -> decltype(auto) {
        return forwarded(f)(forwarded(x)...);
    }
```

How `is_callable<F(Ts...)>` style  it is problematic?

**Comment by pfultz2** [comment]
> How is_callable<F(Ts...)> style it is problematic?

It decays arrays to pointers and discards top-level cv-qualifiers. This can produce incorrect results.

**Comment by viboes** [comment]
I don't see how this problems disappear with `is_callable<Fn, Args...>` style?

**Comment by pfultz2** [comment]
> I don't see how this problems disappear with is_callable<Fn, Args...> style?

The problem doesn't exist. For example, `is_callable<F, int[3]>` will check if `F` is callable with `int[3]`, but `is_callable<F(int[3])>` will check if `F` is callable with `int*`, which is different.

**Comment by viboes** [comment]
I don't reach to see why `is_callable<F(int[3])>` will behave differently than `is_callable<F, int[3]>`. Are the definitions different? What are the definitions of both functions that make this different? Sorry, I'm missing something obvious to you.

**Comment by pfultz2** [comment]
> I don't reach to see why is_callable<F(int[3])> will behave differently than is_callable<F, int[3]>.

They are different because of the way C++ works. `is_callable<F(int[3])>` is the same as calling `is_callable<F(int*)>`, whereas `is_callable<F, int[3]>` and `is_callable<F, int*>` are different. You can try it for yourself with the fit library:

```cpp
#include <fit.hpp>

struct F
{
    bool operator()(int (&&arr)[3]) const;
};

struct G
{
    bool operator()(int*) const;
};

template<class Sig>
struct is_callable_sig;

template<class F, class... Ts>
struct is_callable_sig<F(Ts...)>
: fit::is_callable<F, Ts...>
{};

int main() {
    static_assert(fit::is_callable<F, int[3]>(), "Callable");
    static_assert(is_callable_sig<F(int[3])>(), "Not Callable with function signature");

    static_assert(fit::is_callable<G, int*>(), "Callable");
    static_assert(is_callable_sig<G(int*)>(), "Callable");
}
```

The above will break with `static_assert` failure saying "Not Callable with function signature".

**Comment by ldionne** [comment]
As others pointed out, Hana does not provide `std::is_callable` and I would say it is out of scope for Hana to provide this. Actually, the whole `Functional` part should really be part of a separate library (it's not used inside Hana except for examples) and it will eventually be deprecated in favour of Fit.

**Comment by viboes** [comment]
@pfultz2  I'm not sure this is an issue or it was intentional. I believe that you should report it on std-proposal ML.

**Comment by pfultz2** [comment]
> I'm not sure this is an issue or it was intentional.

It is an issue, whether the committee thinks its important is another matter.
