### ISSUE TITLE
Accessing map with result of `decltype_` does not compile

### ISSUE THREAD

**Issue by jacquelinekay** [boostorg/hana#290]
I am trying to index into a `hana::map` using the result of `hana::decltype_` and iterating over the contents of a tuple.

My understanding was that `hana::decltype_` produces a `hana::type_c`, which seemed to be suitable for indexing into my map. I have also tried constructing a key using language decltype and wrapping that in `type_c`, but I got the same error.

Is this incorrect usage?

```
#include <iostream>
#include <boost/hana.hpp>

namespace hana = boost::hana;

enum Id : uint8_t {
  a, b, c
};

constexpr auto id_map = hana::make_map(
    hana::make_pair(hana::type_c<std::string>, Id::a),
    hana::make_pair(hana::type_c<int>, Id::b),
    hana::make_pair(hana::type_c<bool>, Id::c)
  );

int main() {
  hana::tuple<std::string, int, bool> types_tuple;

  hana::for_each(types_tuple, [](const auto & x) {
    std::cout << "ID is: " << id_map[hana::decltype_(x)] << std::endl;
  });
}
```

Gives this error in clang 3.8 (truncated significantly), on current master:

```
/home/jackie/code/cmbml/external/hana/include/boost/hana/optional.hpp:108:9: error: static_assert
      failed "hana::optional::operator* requires a non-empty optional"
        static_assert(detail::wrong<dummy...>{},
        ^             ~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jackie/code/cmbml/external/hana/include/boost/hana/map.hpp:358:52: note: in instantiation of
      function template specialization 'boost::hana::optional<>::operator*<>' requested here
            constexpr std::size_t index = decltype(*MaybeIndex{}){}();
                                                   ^
/home/jackie/code/cmbml/external/hana/include/boost/hana/at_key.hpp:49:23: note: in instantiation
      of function template specialization 'boost::hana::at_key_impl<boost::hana::map_tag,
      void>::apply<const
      boost::hana::map<boost::hana::detail::hash_table<boost::hana::detail::bucket<std::__cxx11::basic_string<char>,
      0>, boost::hana::detail::bucket<int, 1>, boost::hana::detail::bucket<bool, 2> >,
      boost::hana::basic_tuple<boost::hana::pair<boost::hana::type_impl<std::__cxx11::basic_string<char>
      >::_, Id>, boost::hana::pair<boost::hana::type_impl<int>::_, Id>,
      boost::hana::pair<boost::hana::type_impl<bool>::_, Id> > > &, boost::hana::type_impl<const
      std::__cxx11::basic_string<char> >::_>' requested here
        return AtKey::apply(static_cast<Xs&&>(xs), key);
                      ^
```

And a bit further down:
```
In file included from /home/jackie/code/cmbml/external/hana/include/boost/hana.hpp:133:
/home/jackie/code/cmbml/external/hana/include/boost/hana/map.hpp:358:66: error: illegal initializer
      type 'decltype(* MaybeIndex{})' (aka 'void')
            constexpr std::size_t index = decltype(*MaybeIndex{}){}();
                                                                 ^
/home/jackie/code/cmbml/external/hana/include/boost/hana/at_key.hpp:49:23: note: in instantiation
      of function template specialization 'boost::hana::at_key_impl<boost::hana::map_tag,
      void>::apply<const
      boost::hana::map<boost::hana::detail::hash_table<boost::hana::detail::bucket<std::__cxx11::basic_string<char>,
      0>, boost::hana::detail::bucket<int, 1>, boost::hana::detail::bucket<bool, 2> >,
      boost::hana::basic_tuple<boost::hana::pair<boost::hana::type_impl<std::__cxx11::basic_string<char>
      >::_, Id>, boost::hana::pair<boost::hana::type_impl<int>::_, Id>,
      boost::hana::pair<boost::hana::type_impl<bool>::_, Id> > > &, boost::hana::type_impl<const
      std::__cxx11::basic_string<char> >::_>' requested here
        return AtKey::apply(static_cast<Xs&&>(xs), key);
```

**Comment by ricejasonf** [comment]
`hana::decltype_` does not strip const qualifiers so the types are not equal. I do this all of the time and getting around it is a pain. There should be a `hana::decayed_type(blah)` or something.

**Comment by ldionne** [comment]
Even __I__ thought it would strip cv-qualifiers. What name shall we use for a decltype that strips everything (not only references)? `raw_decltype_`?

**Comment by jacquelinekay** [comment]
Yeah, I skimmed over the prominent part of the documentation that makes this obvious:  "decltype_ will strip any reference from the object's actual type... However, any cv-qualifiers will be retained." http://www.boost.org/doc/libs/1_61_0/libs/hana/doc/html/structboost_1_1hana_1_1type.html#a7d68ff2275cbb295556d83598f04e39a

I'll throw in `decayed_decltype` as another name suggestion for the suggested convenience function for stripping both references and cv-qualifiers.

Thanks also for adding a more concise error message when accessing a missing key.

**Comment by ldionne** [comment]
I'll keep this open until we have a clear solution for `decltype_` removing cv-qualifiers. The fact that you ran into this problem, Jason has it, and I wasn't able to figure out your problem quickly are all indications that something's missing here.

**Comment by ldionne** [comment]
What about `hana::typeid_`?

**Comment by ldionne** [comment]
After all, it gives back a `hana::type`, which can be seen as some kind of static `std::type_info`.

**Comment by ricejasonf** [comment]
```cpp
                hana::equal(
                  hana::traits::decay(hana::decltype_(path)),
                  hana::first(pair)
                )
```

**Comment by ricejasonf** [comment]
I think `hana::decltype_` itself should strip `const` qualifier or even decay the type completely. It would solve more problems than it creates.

I don't think anyone expects a `hana::type_c<const int>` to come from `hana::decltype_(x);` just as they wouldn't expect it to return a `hana::type_c<const int&>`.

If we have to make a new function, I'd suggest deprecating the use of `hana::decltype_` in favor of the new one to avoid further confusion.

**Comment by jacquelinekay** [comment]
I was going to say that it would be confusing if `hana::decltype_` stripped const qualifiers because it defies the expectation set by the behavior of language `decltype`, but then again, it already breaks that expectation by stripping references. I think this usage if an existing keyword is what leads to the confusion in the first place: the analogous Hana behavior is halfway between language decltype and a function that produces a `type_c` for a pure type.

I like the name `typeid_` a bit better because language `typeid` strips const qualifiers and references, though it does not strip pointer types.

Keeping `decltype_` as is and introducing a new function to strip cv qualifiers is not very useful in Hana because cv qualifiers, like references qualifiers, are essentially meaningless for compile-time type-value computation. My impression is that a metafunction that takes a `type_c` shouldn't care if about the qualifiers that affect the runtime behavior of a value of that type, although I'd be curious if anyone can come up with a counterexample.

**Comment by ricejasonf** [comment]
That makes sense. I like `hana::typeid_` too then.

**Comment by ldionne** [comment]
`hana::typeid_` would faithfully model the stripping of ref-qualifiers and cv-qualifiers from whatever you put into it. It wouldn't strip pointers, however, just like `typeid`. I can't change the behavior of `decltype_` because it would be an interface breaking change. Instead, I'll add `typeid_`.

**Comment by ldionne** [comment]
Quick question: would `typeof` be better?

**Comment by ricejasonf** [comment]
`typeof` lacks the trailing underscore so that is a plus. slightly more terse

It might confuse javascript programmers though. :laughing:  (lol jk)

But seriously yeah `typeof`. :+1:
