### ISSUE TITLE
std::array adaptor fails for movable but non-copyable types

### ISSUE THREAD

**Issue by iolojz** [boostorg/hana#304]
Attempting to turn a rvalue of type `std::array<Foo, N>` into a `boost::hana::tuple<...>` when `Foo` is non-copyable but movable does not work.  e.g.

    #include <boost/hana.hpp>
    #include <boost/hana/ext/std/array.hpp>
    
    struct Foo
    {
        Foo( void ) = default;
        Foo( const Foo & ) = delete;
        Foo( Foo && ) = default;
    };
    
    using bar = decltype(boost::hana::to_tuple( std::array<Foo, 42>() ));
    
    int main( void )
    {
        return 0;
    }

does not compile.

**Comment by ricejasonf** [comment]
Hana is using `operator[]` to get the elements from the array which apparently doesn't not support rvalues. Using `std::get<n>` fixes it. I'll submit a PR momentarily.

**Comment by ldionne** [comment]
Fixed by #305.
