### ISSUE TITLE
Add set-theoretic functions for hana::map

### ISSUE THREAD

**Issue by shreyans800755** [boostorg/hana#341]
Add intersection and difference interface for hana::map like operation<map_tag, map_tag>.

**Comment by ldionne** [comment]
From Gitter (posting here because it's easier to track discussions, rationales & al):

> For intersection of `hana::map`, if there's a key k in both maps `m1` and `m2` with values respectively `v1` and `v2`. What should the intersection function return? I can see couple of options:
> 1. Return `hana::map` with pair `{k: v1}`
> 2. Return `hana::map` with pair `{k: pair{v1, v2}}`

A third option is to return `hana::map` with pair `{k, v2}`. However, I think we should be consistent with `hana::union_` and return `{k: v1}`. What do you think?

**Comment by shreyans800755** [comment]
Yeah, I think that's better. 2nd option looks like variation of multimap. By the way, is there any plan for including multimap and multiset in hana ?

**Comment by ldionne** [comment]
> By the way, is there any plan for including multimap and multiset in hana?

Sorry for the late reply, I somehow missed that. Right now, there is no plan to have that, but I would welcome a PR that adds them (if they can be reasonably compile-time efficient).

**Comment by ldionne** [comment]
Closed by #350.
