### ISSUE TITLE
support Microsoft Visual C++ Compiler 15.0

### ISSUE THREAD

**Issue by vincent-hui** [boostorg/hana#351]
Can hana supports Microsoft Visual C++ Compiler 15.0 which is installed by Visual Studio 2017

**Comment by MarcelRaad** [comment]
This is not trivial, unfortunately. I've started to look into what changes would be required to get the tests and examples to at least compile here:
https://github.com/MarcelRaad/hana/tree/msvc

But besides the known limitations, there are a lot of ICE's which mostly disappeared when trying to create minimal repros :-(

**Comment by ldionne** [comment]
Short answer is no, it's not possible to do it. More information at #334, of which this is a duplicate.

**Comment by Bulat-Ziganshin** [comment]
Can you reinvestigate that since MSVC made two compiler updates - in 2017.3 and 2017.5 versions. Also, i propose to clearly document which MSVC versions DOESN'T work since wiki page wasn't updated since 2016, giving false feeling that recent MSVC versions weren't yet tested at all

**Comment by ldionne** [comment]
I don't have local access to MSVC and I've personally never tested on MSVC. If you care about recent MSVCs and have access to it locally, I would greatly appreciate if you could try building and report the results here (so I can edit the wiki) or on the wiki directly.

**Comment by MarcelRaad** [comment]
I'm still testing it from time to time. The situation has improved with Update 6 Preview 1, but there are still a few hundred compile errors in the examples and tests even with the above workarounds (down from a few thousands in 2017 RTM). The compute_info call in group.hpp still ICEs, which affects multiple examples and tests.

**Comment by vincent-hui** [comment]
@MarcelRaad did you try Clang in Visual Studio 2017? https://blogs.msdn.microsoft.com/vcblog/2017/03/07/use-any-c-compiler-with-visual-studio/

**Comment by MarcelRaad** [comment]
@vincent-hui Yes, both clang-cl and the last version of clang/c2 work perfectly.

**Comment by rdilipk** [comment]
Its is extremely unclear exactly what version of MSVC can support building Hana. I have VS 2017 update 15.6.6 which is the latest and the greatest. It does seem to have support for variable templates flagged in this piece: <https://github.com/boostorg/hana/wiki/General-notes-on-compiler-support> as the reason why MSVC is not supported. The only drawback is MSVC still doesn't report the value of __cplusplus correctly but beyond that I get a whole bunch of errors and its hard to tell exactly which aspect of the language feature is lacking that makes it impossible to build in MSVC.

Does anyone know?

**Comment by ricejasonf** [comment]
It would be interesting to see this error list. I don't use MSVC.

**Comment by rdilipk** [comment]
Here is a sample list of errors from index_if.hpp:

    include\boost\hana\index_if.hpp(80): error C2146: syntax error: missing
'>' before identifier 'value'
    include\boost\hana\index_if.hpp(83): note: see reference to class
template instantiation
'boost::hana::index_if_impl<Tag,boost::hana::when<boost::hana::Foldable<T>::value>>'
being compiled
    include\boost\hana\index_if.hpp(80): error C2993: 'unknown-type':
illegal type for non-type template parameter 'N'
    include\boost\hana\index_if.hpp(81): error C2993: 'unknown-type':
illegal type for non-type template parameter 'N'
    include\boost\hana\index_if.hpp(81): error C2144: syntax error:
'unknown-type' should be preceded by ';'
    include\boost\hana\index_if.hpp(81): error C2238: unexpected token(s)
preceding ';'
    include\boost\hana\index_if.hpp(82): error C2988: unrecognizable
template declaration/definition
    include\boost\hana\index_if.hpp(82): error C2059: syntax error: '<end
Parse>'
    include\boost\hana\index_if.hpp(82): error C2334: unexpected token(s)
preceding '{'; skipping apparent function body

I believe our boost version is 1.66.0.

**Comment by ldionne** [comment]
MSVC does not support Hana, period. They have Hana as part of their test cases, and I expect they will report it explicitly when they get Hana to build.

**Comment by rdilipk** [comment]
Ok. That's far more assertive. Thanks Louis! Guess I will stick with Fusion
and MPL for the time being.

**Comment by debugx** [comment]
Why MSVC does not support Hana?
I tryed to build one simple project which uses Hana in VS2015 and VS2017.
There are a lot of errors.
In VS2017 with all last updates the following errors appeared:
boost\hana\index_if.hpp(80): warning C4346: 'boost::hana::Foldable<T>::value': dependent name is not a type
boost\hana\index_if.hpp(80): note: prefix with 'typename' to indicate a type
boost\hana\index_if.hpp(83): note: see reference to class template instantiation 'boost::hana::index_if_impl<Tag,boost::hana::when<boost::hana::Foldable<T>::value>>' being compiled
boost\hana\index_if.hpp(80): error C2146: syntax error: missing '>' before identifier 'value'
boost\hana\index_if.hpp(80): error C2993: 'unknown-type': illegal type for non-type template parameter 'N'
boost\hana\index_if.hpp(81): error C2993: 'unknown-type': illegal type for non-type template parameter 'N'
boost\hana\index_if.hpp(81): error C2144: syntax error: 'unknown-type' should be preceded by ';'
boost\hana\index_if.hpp(81): error C2238: unexpected token(s) preceding ';'
boost\hana\index_if.hpp(82): error C2988: unrecognizable template declaration/definition
boost\hana\index_if.hpp(82): error C2059: syntax error: '<end Parse>'
boost\hana\index_if.hpp(82): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
boost\hana\detail\unpack_flatten.hpp(58): error C2146: syntax error: missing '>' before identifier 'value'
boost\hana\detail\unpack_flatten.hpp(59): error C3545: 'Lengths': parameter pack expects a non-type template argument
boost\hana\detail\hash_table.hpp(50): error C2146: syntax error: missing ';' before identifier 'type'
boost\hana\detail\hash_table.hpp(52): note: see reference to class template instantiation 'boost::hana::detail::find_indices<Map,Key>' being compiled
boost\hana\detail\hash_table.hpp(50): error C2208: 'boost::hana::type': no members defined using this type
boost\hana\detail\hash_table.hpp(116): error C2146: syntax error: missing ';' before identifier 'type'
boost\hana\detail\hash_table.hpp(118): note: see reference to class template instantiation 'boost::hana::detail::bucket_insert<boost::hana::detail::hash_table<Buckets...>,Key,Index,true>' being compiled
boost\hana\detail\hash_table.hpp(116): error C2208: 'boost::hana::type': no members defined using this type
boost\hana\detail\hash_table.hpp(123): error C2146: syntax error: missing ';' before identifier 'type'
boost\hana\detail\hash_table.hpp(125): note: see reference to class template instantiation 'boost::hana::detail::bucket_insert<boost::hana::detail::hash_table<Buckets...>,Key,Index,false>' being compiled
boost\hana\detail\hash_table.hpp(123): error C2208: 'boost::hana::type': no members defined using this type
boost\hana\detail\hash_table.hpp(140): error C2146: syntax error: missing '>' before identifier 'type'
boost\hana\detail\hash_table.hpp(142): note: see reference to class template instantiation 'boost::hana::detail::make_hash_table<KeyAtIndex,N,std::integer_sequence<::size_t,i...>>' being compiled

**Comment by Bulat-Ziganshin** [comment]
>Why MSVC does not support Hana?

@debugx  With 15.7 version, MS announced full support for C++17, but now they report that they still have some bugs in the implementation. Hana is extremely extensive user of new C++ features, so its code employs some features still breaking 15.7. 

Since MSVC team includes Hana in the list of libraries compiled to check C++17 compatibility of MSVC, I believe that they will fix these bugs ASAP. So, just subscribe to this Issue and wait...
