### ISSUE TITLE
FindHana.cmake is not there anymore, but the tutorial still mentions it

### ISSUE THREAD

**Issue by ldionne** [boostorg/hana#356]
Thanks to Michael Park for the notice.

**Comment by ldionne** [comment]
Actually, it turns out that this was only because I merged `develop` into `master` and it took some time to regenerate the documentation. I had correctly fixed the documentation when I moved to modern CMake dependency management (using `HanaConfig.cmake` in d53ef246). @mpark just happened to look just at the wrong moment!

**Comment by mpark** [comment]
😅
