### ISSUE TITLE
noexcept?

### ISSUE THREAD

**Issue by bebuch** [boostorg/hana#363]
Hi Louis, why don't you use `noexcept` in most of your code? It's not important, I'm just interested.

**Comment by ldionne** [comment]
Sorry for the slow reply, I was on vacation. The reason for not using `noexcept` is just simplicity, a bit like the standard library, which only talks about `noexcept` when it makes an obvious difference. For Hana I simply did not do it. Also, given the metaprogramming nature of Hana, I think there are _fewer_ places where it would matter, but there are certainly places where it would. It's just a lot of work and seemed like the return on investment would be minimal. If there are places where you think `noexcept` would be a worthwhile addition, feel free to open a PR.
