### ISSUE TITLE
How to strip a parameter pack from a hana-defined struct for use in tuple initialization?

### ISSUE THREAD

**Issue by invexed** [boostorg/hana#370]
Hi,

I have defined a struct like so, using `BOOST_HANA_DEFINE_STRUCT`:

```
struct A
{
    BOOST_HANA_DEFINE_STRUCT(A,
        (B1, b1),
        (B2, b2),
        (B3, b3)
    );
};
```

How can I initialize an `std::tuple` (or `hana::tuple`) of `std::vector`s of types aliased in `B1`, `B2` and `B3`?

```
std::tuple<
    std::vector<B1::value_type>
    std::vector<B2::value_type>
    std::vector<B3::value_type>
> my_tuple;
```

Thanks in advance for any help you can offer.

**Comment by ricejasonf** [comment]
For starters, you're gonna want some commas. :stuck_out_tongue: 

To get the types of the members of a `hana::Struct` you could use `hana::members`.

Something like this would work:
```cpp
auto make_my_tuple = [](auto ...members)
{
  return hana::type<hana::tuple<std::vector<typename decltype(members)::value_type>...>>{};
};

using MyTuple = typename decltype(hana::unpack(hana::members(std::declval<A>()), make_my_tuple))::type;
```

:coffee:

**Comment by invexed** [comment]
I've got no hope with TMP if I can't even handle a couple of commas!

Thanks so much for your time; it worked like a charm. I'll close the issue now.
