### ISSUE TITLE
Header file missing 

### ISSUE THREAD

**Issue by pree-jackie** [boostorg/hana#387]
Hi 
I'm new to boost.hana and I got some problems when I use boost.hana.
Recently I installed boost.hana with the following commands 
I have the source files in /home/praveen/boost.hana/hana-master. And I created a directory using mkdir build && cd build. 
To install 
1) cmake /home/praveen/boost.hana/hana-master -DCMAKE_INSTALL_PREFIX=/home/praveen/boost.hana/install_dir.
2) cmake --build . --target install
Project is installed successfully. 

Trying with simple program 
```c++ 
#include </home/praveen/boost.hana/install_dir/include/boost/hana.hpp>

namespace hana = boost::hana;
int main()
{
  int i=0;
  
 return 0;
}
```

and tried to compile with clang++ -std=c++14 filename.cpp 
compilers produce error such as 
In file included from hana.cpp:1:

/home/praveen/boost.hana/install_dir/include/boost/hana.hpp:45:10: 
fatal error: 'boost/hana/config.hpp' file not found
#include <boost/hana/config.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

How I can get boost.hana compilation correct ? 
Sorry this is not an issue, I don't know where to ask, I will close once I get the compilation correct 
Thanks
Pree

**Comment by ricejasonf** [comment]
You need to have the contents of the `include` directory in the include path.

It would look something like this:
```
clang++ -std=c++14 -I/home/praveen/boost.hana/install_dir/include filename.cpp
```
Then in your code you would have to use `#include <boost/hana.hpp>`

Or.. just install Boost.Hana's headers to `/usr/local/include` or use cmake.

**Comment by ldionne** [comment]
Thanks Jason.

**Comment by pree-jackie** [comment]
@ricejasonf @ldionne 
Thank you very much guys ! It compiles successfully :+1:
