### ISSUE TITLE
BOOST_HANA_CONFIG_ENABLE_STRING_UDL isn't always checked

### ISSUE THREAD

**Issue by xiangfan-ms** [boostorg/hana#401]
The user defined literal '_s' is only available when the macro BOOST_HANA_CONFIG_ENABLE_STRING_UDL is defined. It depends on a GCC extension.

Three tests under hana\example\map use it without checking the macro. You can find them by searching for macro 'BOOST_HANA_WORKAROUND_MSVC_NO_STRING_UDL' in the repo https://github.com/xiangfan-ms/hana.

**Comment by ldionne** [comment]
Thanks for the report. Will be fixed.
