### ISSUE TITLE
Warning when using std::unique_ptr<T[N]>

### ISSUE THREAD

**Issue by xiangfan-ms** [boostorg/hana#402]
MSVC will emit a warning when compiling std::unique_ptr<T[N]> because default_delete<T[N]> has undefined behavior. See https://github.com/boostorg/hana/blob/master/test/tuple/smart_ptr.cpp for details.

Other compilers don't complain likely because warnings are suppress for system headers.

All compilers give warning if it is used in user code:

	#include <memory>

	void f(char(*p)[5])
	{
		std::default_delete<char[5]> d;
		d(p); // no warning in clang/gcc

		delete p; // warning
	}

There is an ongoing discussion in LWG on whether a partial specialization should be added for 'T[N]'.
But in the current state, we believe the warning is legit.

**Comment by ldionne** [comment]
Thanks for the report -- will fix.
