### ISSUE TITLE
silence MSVC warning in config.hpp for latest MS compilers

### ISSUE THREAD

**Issue by tobias-loew** [boostorg/hana#418]
the warning in line 23 in config.hpp could be silenced for latest MSVC compilers (e.g. there could be a test for the value of __cplusplus)

**Comment by ldionne** [comment]
Can you check whether this has been resolved since https://github.com/boostorg/hana/pull/419 was merged?

**Comment by tobias-loew** [comment]
Yes, #419 solves this. Thanks!
