### ISSUE TITLE
Typo in hana manual "generic lifting process" (Trac ticket #13572)

### ISSUE THREAD

**Issue by mloskot** [boostorg/hana#423]
(copied from https://svn.boost.org/trac10/ticket/13572 BTW, Trac seem to be missing component for `hana`)

This page:
https://www.boost.org/doc/libs/1_67_0/libs/hana/doc/html/index.html#tutorial-type-lifting
contains:

```
return hana::type<T*>;
```

This fails clang compilation. When changed to:

```
return hana::type_c<T*>;
```

it passes clang compilation.

**Comment by ricejasonf** [comment]
Perhaps we should change it to
```cpp
return hana::type<T*>{};
```
Louis uses that form in his slides claiming it was better for teaching newcomers.

**Comment by ldionne** [comment]
Thanks a lot for reporting -- I did not realize some people were filing bugs in Trac.

**Comment by ldionne** [comment]
@ricejasonf I uses `type_c` for consistency with the rest of the tutorial.
