### ISSUE TITLE
semantics of naming

### ISSUE THREAD

**Issue by ohhmm** [boostorg/hana#426]
Traditional boost naming strategy is to use best match by semantics.
Please, consider renaming this library to make its goal self-descriptive.
For example 'metaprograming' or 'mmpl' (Modern Meta-Programing Library acronym) seems best match.

**Comment by ricejasonf** [comment]
You should keep an [openmind](https://github.com/ohhmm/openmind) about how people name their libraries. :stuck_out_tongue:

**Comment by ohhmm** [comment]
Actually openmind is not a boost library and was not intended for STL.

**Comment by ohhmm** [comment]
Yes, we should address these libraries too.

**Comment by apmccartney** [comment]
> let's break API because I don't like the name

**Comment by ohhmm** [comment]
I can't say I don't like the name. I didn't say we should break API. Sure we can leave alias to old name. I say there is better chance for standardization with a name which would say the closest best match to the entity semantics.

**Comment by ldionne** [comment]
Sorry, we're not going to rename the library.
