### ISSUE TITLE
MSVC support did not make it in 1.69 (Hana 1.5) but the documentation says otherwise

### ISSUE THREAD

**Issue by sdebionne** [boostorg/hana#433]
For anyone wondering why Hana does not compile on MSVC while the documentation says it is now fully supported, it's just that the documentation if slightly "ahead of time". The `develop` branch works fine.

**Comment by sdebionne** [comment]
TBH, I was disappointed to see that MSVC support did not make it to Boost 1.70 neither. Any chance to get Hana 1.5.1 with the patch from MS in 1.71?

**Comment by ldionne** [comment]
Sorry, I got very busy and missed the deadline 🤦‍♂️. I'm tagging 1.6.0 and merging to master right now to make sure I don't miss 1.71.0
