### ISSUE TITLE
constexpr variable specialization needs inline with clang 9

### ISSUE THREAD

**Issue by mgaunard** [boostorg/hana#459]
I get multiple definitions of curry_or_call<0>

**Comment by ricejasonf** [comment]
This has a fix in the development branch: https://github.com/boostorg/hana/commit/7218a046c731b2548b5ae3db55fb711ccda8fbc4

**Comment by mgaunard** [comment]
sorry I didn't catch that this was fixed by using an anonymous namespace since 1.71.
