### ISSUE TITLE
Is it OK to specialize *_impl templates for user-defined types?

### ISSUE THREAD

**Issue by 60rntogo** [boostorg/hana#468]
I would like to make my custom type satisfy, say, the `Functor` concept. This seems to work if I provide specialization of `transform_impl`, but I couldn't find anything about this in the documentation. Only specializing `accessors_impl` appears to be documented. Is this an officially supported feature?

**Comment by ldionne** [comment]
Yes, that's the standard way of doing so. The details of the `xxx_impl` mechanism are documented here: http://boostorg.github.io/hana/index.html#tutorial-core.

When a concept documents a minimal complete definition, it means that for any type to model that concept, the corresponding `xxx_impl` functions need to be defined. For example, for [Functor](http://boostorg.github.io/hana/group__group-Functor.html), it means that either `transform_impl` or `adjust_if_impl` must be defined *and* satisfy the properties documented in the concept.

**Comment by ldionne** [comment]
Please close if this answers your question, otherwise I'll try to clarify.

**Comment by 60rntogo** [comment]
OK, thanks. That certainly answers my question, I just didn't look hard enough. I read most of the user manual, but didn't get all the way down to the core section which is my bad. On the other hand, I tried searching the documentation for `transform_impl` and `unpack_impl` and neither returned any hits which sent down the wrong path of wondering if these things are implementation details.
