### ISSUE TITLE
How to use hana containers as class data members?

### ISSUE THREAD

**Issue by impugachev** [boostorg/hana#499]
For example, I want to write something like this in a class method.
```c++
if constexpr (boost::hana::contains(this->map_, "name"_s)){
    std::cout << this->map_["name"_s] << std::endl;
}
```
Unfortunately, c++ prohibits the use of `this` in `if constexpr`. How am I supposed to use hana here? Sorry if this has already been asked, I couldn't find anything similar.

[Full example](https://godbolt.org/z/jfoEKxM8T) 
[Stupid workaround](https://godbolt.org/z/Gx3scTqrb)

**Comment by ldionne** [comment]
Here's another way to do it: https://godbolt.org/z/W41K57cb6

The fundamental limitation here is that the language sees you are reading `this->...` inside a constant evaluated context and it bails out.
