### ISSUE TITLE
Is it possible to get back the C++ type from hana::type?

### ISSUE THREAD

**Issue by Kelvinyu1117** [boostorg/hana#513]
Hi everyone, I'm new to hana and I want to play around with some metaprogramming magic with hana.

Is there any function that allows me to convert `hana::type<T>` back to `T`?

**Comment by ricejasonf** [comment]
The simplest, most common way to access the contained type is via the `type` member: `typename some_type::type`.
Other techniques may involve type deduction, and there is also the `Metafunction` concept which provides a few functions for applying types to templates in various ways.

Be sure to check out the "Lvalues and Rvalues" section under the documentation for `type`.
http://boostorg.github.io/hana/structboost_1_1hana_1_1type.html
