### ISSUE TITLE
[String] Reconsider the representation

### ISSUE THREAD

**Issue by ldionne** [boostorg/hana#69]
Right now, we use a different template specialization to store each different string. This could also work by using an anonymous type, but there seems to be a bug in Clang right now that makes this in some circumstances: http://llvm.org/bugs/show_bug.cgi?id=20625. Using an anonymous type could have compile-time performance benefits, so this avenue should be explored once the bug is fixed.

**Comment by cbsmith** [comment]
20625 is marked as resolved fixed as of 2015-04-28.

**Comment by ldionne** [comment]
@cbsmith That is totally correct, thanks for the heads up. I'll try to find the time to benchmark this.

**Comment by badair** [comment]
Can you explain the term "anonymous type"? Is it struct with no name, or a struct generated by a lambda?

**Comment by ldionne** [comment]
> Can you explain the term "anonymous type"? Is it struct with no name, or a struct generated by a lambda?

I mean any type that is not _well-defined_, for some definition of well-defined. :-) Basically, it could be a lambda type, or even a local struct defined inside a lambda:

```c++
auto f = []{ struct local { /* ... */ };  return local{}; };
using Local = decltype(f());
```

These _weird_ types have the property of sometimes making symbols shorter, because they "erase" information about template parameters that can sometimes grow long. However, I think this is not the case with Clang, where the name of lambda type actually contains the context in which it was instantiated.

Reducing the length of symbols might (or not) be an interesting optimization to apply, which is essentially the question behind this issue.

**Comment by ldionne** [comment]
But yeah, I guess a struct with no name would also fit to that description. I was referring to _weird_ types that have the property of reducing symbol length in general.

**Comment by badair** [comment]
Wow, that is a very interesting idea. Are hana strings currently a performance bottleneck? Are there any data on the performance implications of symbol length in Clang? I would guess that symbols spend most of their lives in a hash table, but I've never looked at Clang code.

**Comment by ldionne** [comment]
Well right now they surely aren't a performance bottleneck. However, I can easily imagine an application that makes heavy use of compile-time strings see its compile-times go way up. This could be because of the representation, or because of the operations on strings, or anything else. This might also not be the case at all, and perhaps this issue does not exist.

To settle on this issue, we should benchmark some uses of compile-time strings, and if it seems to be problematic, try to see if we can improve it. Everything is still left to be done.

**Comment by ldionne** [comment]
I did some benchmarks (available in [this Gist](https://gist.github.com/ldionne/2277947fb9fc82fe6c02)). The results are that using an anonymous type seems more efficient on Clang, and less efficient on GCC.

GCC:
![gcc](https://cloud.githubusercontent.com/assets/700834/12874356/8dd5ab6e-cda0-11e5-9c44-5e3e8f4fe375.jpeg)

Clang: 
![clang](https://cloud.githubusercontent.com/assets/700834/12874359/94114574-cda0-11e5-9e75-b733d6288317.jpeg)

Here, `anonymous type` uses a lambda to erase the type that contains the compile-time string, and `struct` is just the approach we use currently, i.e. `template <char ...s> struct string { ... };`.

**Comment by ldionne** [comment]
Since this issue has been opened, I have come to prefer the representation of strings as a parameter pack of `chars` since it provides better debug-ability over anonymous types. Furthermore, I will argue that
1. both approaches don't scale to very large sizes
2. the metaprogramming required to deal with such large strings would probably explode compile-times way before the string representation does

Hence, I'll close this and keep the current representation. Overall, this issue will be better addressed by a language feature, which we are exploring as part of solving compile-time programming.

__If you have a use case where the current representation of strings is a problem, let me know and we might revert this decision, but otherwise I would say you need to deal with it differently, e.g. by anonymizing the strings yourself.__
